spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        # 认证中心
        - id: gjk-auth
          uri: lb://gjk-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - ValidateCodeGatewayFilter
            # 前端密码解密
            - PasswordDecoderFilter
        #UPMS 模块
        - id: gjk-upms
          uri: lb://gjk-upms
          predicates:
            - Path=/admin/**
          filters:
            # 限流配置
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        # 代码生成模块
        - id: gjk-codegen
          uri: lb://gjk-codegen
          predicates:
            - Path=/gen/**
            
        # 构件模块
        - id: gjk-component
          uri: lb://gjk-component
          predicates:
            - Path=/comp/**
            
        # 项目设计模块
        - id: gjk-project
          uri: lb://gjk-project
          predicates:
            - Path=/pro/**
        # 库管理模块
        - id: gjk-libs
          uri: lb://gjk-libs
          predicates:
            - Path=/libs/**
        # 数据中心模块
        - id: gjk-dataCenter
          uri: lb://gjk-dataCenter
          predicates:
            - Path=/dataCenter/**
        # 编译中心模块
        - id: gjk-compile
          uri: lb://gjk-compile
          predicates:
            - Path=/compile/**
       

security:
  encode:
    # 前端密码密钥，必须16位
    key: 'thanksU,inforbus'

# 不校验验证码终端
ignore:
  clients:
    - test
