## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(27v1agvAug87ANOVnbKdsw==)
      client-secret: ENC(VbnkopxrwgbFVKp+UxJ2pg==)
      scope: server

spring:
  # 数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/gjk?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  resources:
    static-locations: classpath:/static/,classpath:/views/
#management:
#  metrics:
#    web:
#      server:
#        auto-time-requests: false
#zipkin:
#  storage:
#    type: mysql
#sleuth:
#  enabled: true
  
# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /log/**
    - /component/**
    - /componentdetail/**